# Generated by Django 3.1.2 on 2020-11-19 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20201118_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.account'),
        ),
    ]
